README.md
Providing an article about event ticketing
=> Add critical views of specific uses cases

README.md
This PR adds [web3 is going just great](https://web3isgoinggreat.com/) by Molly White
=> Add web3 is going just great

README.md
TIL : https://www.usenix.org/publications/loginonline/web3-fraud
=> Adds "The Web3 Fraud" by Nicholas Weaver on usenix

README.md
Included `The Myth of Decentralization and Lies about Web 2.0` by Emily Gorcenski
=> Added `The Myth of Decentralization and Lies about Web 2.0`

README.md
=> Correct Matt Levine article date

README.md
Put very short summary with article link. Seems it could fit multiple places.
=> Add Lyn Alden article to inbox

README.md
Added a foreword regarding content in that section too. Ditched the awkward 'Twitterers' too.
=> Updated Twitter section

README.md
Changed to lowercase the initial letters of some words for consistency.
=> adds suggestions, grammar

README.md
Added Twitter microblogs for smdiehl.
=> Add Criticism Microblogs

README.md
This PR adds some articles mostly picked from [r/anticryptocurrency](https://reddit.com/r/anticryptocurrency) and takes the opportunity to reformat a couple existing entries.
=> add a few articles

README.md
This topic is related to Stablecoins, but seemed distinct enough for its own section.
=> Add Central Bank Digital Currency section

README.md
Adds entry to
https://www.youtube.com/watch?v=YQ_xWvX1n9g
I was wondering if we could organise videos in a dedicated session later; for now just left a parenthesis mentioning this is a documentary (hence, video content).
=> Adds link to Youtube documentary by Dan Olson

README.md
The classic — still a really good resource!
=> Add the "Burn It With Fire" presentation video

README.md
Covers NFTs, their road to feudalism, and his work on Valve economics. Fixes original PR
=> Adds interview with Yanis Varoufakis

README.md
Econ articles sorted by date as they are responding to emerging changes in the ecosystem and it seemed to make more sense to view them chronologically.,
=> Added new Tyler Cowen, sorted econ articles, added response to Dan Olson

README.md
Seeing the comment at the bottom - "New topic concerning the psychological harm, such as: gambling, greed, cultism, etc." I was encouraged to suggest these.
Obviously I understand that many or most of your readers are not going to be religious, but religion, and Christianity in particular, is a very important part of western culture and thinking, so I think these could be valuable voices to add.
I've read the two articles and I think they are very high quality — Joe Carter always writes very well researched things, and he has not let himself down with this. While both articles are strongly critical of Bitcoin, they remain fair and balanced in their assertions. For example, Carter freely acknowledges that the pornography industry has been instrumental in driving useful internet …
=> Added some links from a Christian perspective.

README.md
Fixes https://github.com/rufuspollock/awesome-crypto-critique/issues/28
=> Add posts by Kai Stinchcombe and Jesse Frederik

README.md
Can be renamed/collapsed into others if desired
=> Add trading/security risk section

README.md
Linked interview : [Internet guru Tim O'Reilly on Web3: "Get ready for the crash"](https://www.cbsnews.com/news/cryptocurrency-nft-blockchain-web3-tim-oreilly/)
Important excerpt : 
> CBS MoneyWatch spoke with tech luminary Tim O'Reilly, who among other things in his long career is known for publishing the world's [first website](https://www.historyofinformation.com/detail.php?entryid=1304) and coining the term [Web 2.0](https://www.oreilly.com/pub/a/web2/archive/what-is-web-20.html).
=> Links interview from Tim O'Reilly to CBS

README.md
... Can We Mitigate Cryptocurrencies' Externalities?
=> suggesting David Rosenthal

README.md
I've published a few more essays that aren't listed here yet. Thanks for maintaining this wonderful resource!
=> + newer essays by Molly White

README.md
=> Tim O'Reilly on Web3

guide/index.md
=> Fix typo in guide

guide/index.md
The headings I changed were marked up as regular, bold text, rather than as headings. That makes them harder to find for users of assistive technologies like screenreaders.
=> Use headings for headings

site/components/Layout.js, site/components/Nav.js, site/config/siteConfig.js
=> [site/theme,#70]: add social links to nav and footer

notes/fintech-incrementalism-and-responsible-innovation.md
I'm testing making edits as someone outwith the organisation for the editors' guide. Please ignore.
=> Eilidh testing for editor guide. added full stop

concepts/consensus-algorithm.md
Fixing typo (and following the process of doing this for the purpose of developing the editors' guide).
=> Removal of extra full stop

site/package-lock.json, site/pages/concepts.js
Resolves #94 
PR includes:
Page that lists all page links belonging to concepts.
[x] create index page for concepts at `/concepts`
=> [site/pages]: create index page for concepts

site/components/Home/Features.js, site/components/Home/Get-Involved.js, site/components/Home/Why.js
Use `next/link` to navigate between pages in homepage
=> Use next/link to navigate between pages

guide/interviews.md
Testing proposing changes following website editor guide instructions
=> Add links to eps 5+6

concepts/liquidity.md
=> Broken link for market.md

claims/is-environmental-footprint.md
testing editors guide method 2 with fork, new branch and pull request
=> edit typos

claims/index.md, site/components/Home/Features.js, site/components/Home/Get-Involved.js, site/components/Home/Hero.js, site/components/Home/Why.js, site/content/about.md
- /about and /claims pages: clickable images with coggle trees with links to original coggle projects
- removed the duplicate image in the "We need better sensemaking" section
- adjusted image responsiveness on the front page
- fixed title overflowing image in Hero component
TBD: issue for extracting repeating parts of code into separate reusable components to improve readability and maintainability
=> Various UX/UI fixes

site/hooks/useHeadingsObserver.js, site/styles/global.css
* added small timeout to active heading change to remove short flashes of color change on headings that are visible for very short periods of time when auto scrolling to a given heading (after clicking on its corresponding link in the ToC)
* added a line on the left hend side of the active link in the ToC
=> Adjusted ToC behavior on scroll + minor style change

notes/fintech-incrementalism-and-responsible-innovation.md
Have written steel man and evaluation summary in order to convert what was the fintech deep dive page into the claim page for the "Crypto is enabling more and better financial products and a more efficient market" claim
=> edit fintech deep dive into claim page

claims/is-better-payments.md, notes/bitcoin-as-anti-authoritarian.md
change title, front matter, and reformat into claim and subclaims
=> Eilidh edits antiauthoritarian

claims/opportunity-for-gain.md, meta/editing.md, notes/are-crypto-tokens-securities.md, notes/bitcoin-as-anti-authoritarian.md
Made securities deep dive page into "unregulated trading in securities is desirable" claim page. References have been generated from Zotero folder. Yet to add evidence.
=> Eilidh edits securities

claims/is-better-payments.md, claims/opportunity-for-gain.md, meta/editing.md, notes/bitcoin-as-anti-authoritarian.md
Create claims/opportunity-for-gain
=> Eilidh edits opportunity for gain

claims/is-better-payments.md, claims/opportunity-for-gain.md, meta/editing.md, notes/bitcoin-as-anti-authoritarian.md
Transferred the editing guide onto the site
=> Eilidh edits editing guide

claims/can-solve-collective-action-problem.md, claims/opportunity-for-gain.md, meta/editing.md, notes/are-crypto-tokens-securities.md, notes/bitcoin-as-anti-authoritarian.md
Not finished, still to add evidence and references. Steel man and evaluation added.
=> Eilidh edits collective action

claims/can-solve-collective-action-problem.md, claims/is-environmental-footprint.md, claims/opportunity-for-gain.md, meta/editing.md, notes/are-crypto-tokens-securities.md, notes/bitcoin-as-anti-authoritarian.md
Edited existing page ../claims/is-environmental-footprint.md so as to be consistent with newly refactored claims pages.
=> Eilidh edits environmental footprint
